version: '3'

services:
  influxdb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: influxdb

    ports:
      - "8086:8086"
    volumes:
      - 'influxdb:/var/lib/influxdb'
volumes:
  influxdb:
